apiVersion: cert-manager.io/v1alpha2
kind: certificate
metadata:
  name: multi-k8s-killer-tls
spec:
  secretName: multi-k8s-killer-org #secret in which certificate will be stored, it will be automatically created
  issuerRef: 
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: multi-k8s-killer.org #our website name mostly
  dnsNames: #list of DNS we added in our domain creation
    - multi-k8s-killer.org
    - www.multi-k8s-killer.org 
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - multi-k8s-killer.org
          - www.multi-k8s-killer.org 