apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory # this is the letsencrypt api to be accessed to get the certificates
    email: "santhosh87.v@gmail.com"
    privateKeySecretRef:
      name: letsencrypt-prod-key #just a one time that will be created in this interaction process and will be referenced internally
    solvers:
      - http01: #type of this entire interaction process
          ingress:
            class: nginx